using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ametrin.Serializer.Generator;

[Generator]
public sealed class SerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var nodes = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Ametrin.Serializer.GeneratedConverterAttribute",
            static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
            static (ctx, cancellationToken) => (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.TargetNode, cancellationToken)!
        );

        context.RegisterSourceOutput(nodes, static (context, converterType) =>
        {
            var attribute = converterType.GetAttribute(IsGeneratedConverterAttribute)!;
            var targetType = converterType.AllInterfaces.Single(IsISerializationConverter).TypeArguments[0];
            var serializedTypeName = attribute.ConstructorArguments[0].Value as string ?? targetType.ToString();
            var allProperties = attribute.ConstructorArguments[1].Value is true;
            var allFields = attribute.ConstructorArguments[2].Value is true;

            var serializeMembers = targetType.GetMembers().Where(member => (allProperties && member is IPropertySymbol) || (allFields && member is IFieldSymbol) || member.HasAttribute(IsSerializeAttribute))
                .Select(static member =>
                {
                    var attribute = member.GetAttribute(IsSerializeAttribute);
                    return (symbol: member, name: member.Name, nameLower: member.Name.ToLower(), type: GetMemberType(member), converter: attribute?.ConstructorArguments[0].Value as INamedTypeSymbol);
                })
                .Where(member => member.converter is not null || IsSerializablePropertyType(member.type)).ToImmutableArray();

            if (serializeMembers.Length is 0)
            {
                return;
            }

            var sb = new StringBuilder();

            sb.AppendLine("""
            using Ametrin.Optional;
            using Ametrin.Serializer;

            """);

            if (!converterType.ContainingNamespace.IsGlobalNamespace)
            {
                sb.AppendLine($"namespace {converterType.ContainingNamespace};");
                sb.AppendLine();
            }

            sb.AppendLine("""
            // This file is auto-generated by Ametrin's SerializerGenerator

            #nullable enable
            """);

            var nesting = new Stack<INamedTypeSymbol>();
            for (var containingType = converterType.ContainingType; containingType != null; containingType = containingType.ContainingType)
            {
                nesting.Push(containingType);
            }

            foreach (var containingType in nesting)
            {
                sb.AppendLine($"partial class {containingType.Name}");
                sb.AppendLine("{");
            }

            sb.AppendLine($$"""
            partial class {{converterType.Name}}
            {
                // [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
                // private {{converterType.Name}}({{string.Join(", ", serializeMembers.Select(member => $"{member.type} {member.nameLower}"))}})
                // {
            """);

            // foreach (var (_, name, nameLower, _, _) in serializeMembers)
            // {
            //     sb.AppendLine($$"""
            //         this.{{name}} = {{nameLower}};
            // """);
            // }

            sb.AppendLine($$"""
                // }

                public static void WriteValue(IAmetrinWriter writer, {{targetType.Name}} value)
                {
                    writer.WriteStringProperty("$type", "{{serializedTypeName}}");
            """);


            foreach (var member in serializeMembers)
            {
                sb.AppendLine(member switch
                {
                    { converter: not null } => $$"""
                    writer.WritePropertyName("{{member.name}}");
                    {{member.converter}}.WriteValue(writer, value.{{member.name}});
            """,
                    // { } when member.type.HasAttribute(IsGenerateSerializerAttribute) => $$"""        writer.WriteObjectProperty("{{member.name}}", value.{{member.name}}!);""",
                    { type.TypeKind: TypeKind.Enum } => $$"""        writer.WriteInt32Property("{{member.name}}", (int)value.{{member.name}});""",
                    { } when IsTypeSupportedByWriter(member.type) => $$"""        writer.Write{{member.type.Name}}Property("{{member.name}}", value.{{member.name}});""",
                    _ => throw new InvalidOperationException($"Unsupported member type {member.type} for serialization"),
                });
            }

            sb.AppendLine($$"""
                }

                public static {{targetType.Name}} ReadValue(IAmetrinReader reader) => TryReadValue(reader).OrThrow();

                public static Result<{{targetType.Name}}, DeserializationError> TryReadValue(IAmetrinReader reader)
                {
                    DeserializationError error = default;
                    
            """);

            foreach (var member in serializeMembers)
            {
                sb.AppendLine($$"""
                    var {{member.nameLower}}Result = {{member switch
                {
                    { converter: not null } => $"""reader.TryReadPropertyName("{member.name}").ToResult(reader, static reader => {member.converter}.TryReadValue(reader)).Map(static v => v)""",
                    { } when member.type.HasAttribute(IsGenerateSerializerAttribute) => $"""reader.TryReadObjectProperty<{member.type.WithNullableAnnotation(NullableAnnotation.None)}>("{member.name}")""",
                    { } when IsTypeSupportedByWriter(member.type) => $"""reader.TryRead{member.type.Name}Property("{member.name}")""",
                    { type.TypeKind: TypeKind.Enum } => $"""reader.TryReadInt32Property("{member.name}").Map(static v => ({member.type}) v)""",
                    _ => throw new InvalidOperationException($"Unsupported member type {member.type} for deserialization"),
                }}};
                    if (!{{member.nameLower}}Result.Branch(out var {{member.nameLower}}, out error))
                    {
                        return error;
                    }

            """);
            }

            sb.AppendLine($$"""
                    return new {{targetType.Name}}({{string.Join(", ", serializeMembers.Select(member => member.nameLower))}});
            """);

            // if (!type.InstanceConstructors.Where(static ctor => !ctor.IsImplicitlyDeclared).Any())
            // {
            //     sb.AppendLine($$"""
            //     }

            //     public {{type.Name}}() 
            //     {
            //         // type had no constructors. re-adding implicit constructor
            // """);
            // }

            sb.AppendLine($$"""
                }

                [System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Register()
                {
                    AmetrinSerializer.RegisterSerializer<{{targetType.Name}}>("{{serializedTypeName}}");
                }
            }
            """);

            foreach (var containingType in nesting)
            {
                sb.AppendLine("}");
            }

            context.AddSource($"{converterType.ToDisplayString()}.Serializer.g.cs", sb.ToString());
        });
    }


}
